import Head from "next/head";
import styles from "@app/styles/Home.module.css";
import Image from "next/image";

export default function DefaultLayout({children}) {
  return <>
    <Head>
      <title>UGMK TEST APP</title>
      <meta name="description" content="Generated by create next app" />
      <meta name="viewport" content="width=device-width, initial-scale=1" />
      <link rel="icon" href="/favicon.ico" />
    </Head>
    <main className={`${styles.main}`}>
      <div className={styles.center}>
        {children}
      </div>
    </main>
  </>
}
